models:
  Project:
    docs: Represents a project within a workspace.
    fields:
      id:
        type: string
      name:
        type: string
      completed:
        type: boolean
      order:
        type: int
      createdBy:
        type: string
        optional: true
