# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build the project
          command: yarn run build
      - run:
          name: Check if repo contains the correct JSON schema for the current version
          command: |
            yarn run generate-json-schema
            git --no-pager diff --exit-code
      - persist_to_workspace:
          root: .
          paths: [.]

  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Eslint checks
          command: yarn run lint
      - run:
          name: Run Prettier checks
          command: yarn run format-check

  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run rests
          command: yarn test

  publish:
    executor: node/default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: secrets/hosting-service-account-prod.json
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install the Firebase CLI
          command: yarn global add firebase-tools@13.5.1
      - run:
          name: Prepare service account
          command: |
            mkdir -p secrets
            echo $HOSTING_SERVICE_ACCOUNT_BASE64_PROD | base64 -d > secrets/hosting-service-account-prod.json
      - run:
          name: Publish JSON schema
          command: firebase deploy --only hosting
      - run:
          name: Delete service account
          command: rm -rf secrets/hosting-service-account-prod.json
      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires: [build]
          filters:
            tags:
              only: /.*/
      - test:
          requires: [build]
          filters:
            tags:
              only: /.*/
      - publish:
          requires: [build, lint, test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
