# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build the project
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths: [.]

  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Eslint checks
          command: yarn run lint
      - run:
          name: Run Prettier checks
          command: yarn run format-check

workflows:
  ts_check:
    jobs:
      - build
      - lint:
          requires: [build]
