# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

commands:
  checkout-build-yarn-project:
    parameters:
      checkout_path:
        type: string
        default: .
    steps:
      - checkout:
          path: << parameters.checkout_path >>
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build the project
          command: yarn run build
jobs:
  build:
    executor: node/default
    steps:
      - checkout-build-yarn-project:
          checkout_path: ~/project
      - persist_to_workspace:
          root: .
          paths: [.]

  generate-typesync-models:
    executor: node/default
    parameters:
      model_path:
        description: Relative/absolute path to the input model .yml file
        type: string
      output_folder_path:
        description: Target output dir of the generated types
        type: string
      platform:
        description: Target platform and version
        type: enum
        enum: ['ts:firebase-admin:12', 'ts:firebase-admin:11', 'ts:firebase:10', 'ts:firebase:9', 'py:firebase-admin:6']
    steps:
      - checkout-build-yarn-project:
          checkout_path: ~/project
      - run:
          name: Generate types from the model schema
          command: |
            PYTHON_OUTPUT_MODEL_PATH=<< parameters.output_folder_path >>/models.py
            yarn tsx src/cli.tsx generate --definition << parameters.model_path >> \
            --platform << parameters.platform >> \
            --outFile $PYTHON_OUTPUT_MODEL_PATH
      - persist_to_workspace:
          root: << parameters.output_folder_path >>
          paths: [.]

  test-typesync-python-end-to-end:
    docker:
      - image: seymurkafkas/python-java-gcloud:latest
    parameters:
      path_to_typesync_model_dir:
        description: Relative/absolute path to the generated python model dir, containing the model file
        type: string
    working_directory: ~/project/tests/test-poetry-project
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: << parameters.path_to_typesync_model_dir >>
      - run:
          name: Install the Poetry project
          command: |
            poetry install
      - run:
          name: Run Python end-to-end tests
          command: |
            TYPESYNC_OUT_MODEL_PATH=<< parameters.path_to_typesync_model_dir >>/models.py poetry run pytest
  lint:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Eslint checks
          command: yarn run lint
      - run:
          name: Run Prettier checks
          command: yarn run format-check

  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run rests
          command: yarn test

  publish-npm-package:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish

  publish-json-schema:
    executor: node/default
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: secrets/hosting-service-account-prod.json
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Check if repo contains the correct JSON schema for the current version
          command: |
            yarn run generate-json-schema
            git --no-pager diff --exit-code
      - run:
          name: Install the Firebase CLI
          command: yarn global add firebase-tools@13.5.1
      - run:
          name: Prepare service account
          command: |
            mkdir -p secrets
            echo $HOSTING_SERVICE_ACCOUNT_BASE64_PROD | base64 -d > secrets/hosting-service-account-prod.json
      - run:
          name: Publish JSON schema
          command: firebase deploy --only hosting
      - run:
          name: Delete service account
          command: rm -rf secrets/hosting-service-account-prod.json

workflows:
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires: [build]
          filters:
            tags:
              only: /.*/
      - test:
          requires: [build]
          filters:
            tags:
              only: /.*/
      - publish-npm-package:
          requires: [build, lint, test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-json-schema:
          requires: [build, lint, test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

  integration-tests:
    jobs:
      - generate-typesync-models:
          model_path: 'tests/test-poetry-project/test_poetry_project/models.yml'
          output_folder_path: 'tests/test-poetry-project/autogen'
          platform: 'py:firebase-admin:6'
      - test-typesync-python-end-to-end:
          requires: [generate-typesync-models]
          path_to_typesync_model_dir: 'tests/test-poetry-project/autogen'
